# Generated by Django 5.0.2 on 2025-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEv', models.CharField(max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('horaInicio', models.TimeField(max_length=20, null=True)),
                ('horaFin', models.TimeField(max_length=20, null=True)),
                ('lugar', models.CharField(max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_json', models.TextField(blank=True, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_breve', models.TextField(blank=True, max_length=300, null=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
